export const MAIN_STATE_CTX = 'MAIN_STATE_CTX';
export const ROUTE_STATE_CTX = 'ROUTE_STATE_CTX';
export const COLLECTION_STATE_CTX = 'COLLECTION_STATE_CTX';
export const DIALOG_STATE_CTX = 'DIALOG_STATE_CTX';
export const COUNT_STATE_CTX = 'COUNT_STATE_CTX';
export const ENTITY_STATE_CTX = 'ENTITY_STATE_CTX';